package com.edityj.chapter2.mapper;

import com.edityj.chapter2.pojo.ProductProperty;
import com.edityj.chapter2.pojo.ProductPropertyExample;
import java.util.List;

public interface ProductPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yj_product_property
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yj_product_property
     *
     * @mbg.generated
     */
    int insert(ProductProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yj_product_property
     *
     * @mbg.generated
     */
    int insertSelective(ProductProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yj_product_property
     *
     * @mbg.generated
     */
    List<ProductProperty> selectByExample(ProductPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yj_product_property
     *
     * @mbg.generated
     */
    ProductProperty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yj_product_property
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yj_product_property
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductProperty record);
}