package com.edityj.chapter2.mapper;

import com.edityj.chapter2.pojo.ProductCategory;
import com.edityj.chapter2.pojo.ProductCategoryExample;
import java.util.List;

public interface ProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yj_product_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yj_product_category
     *
     * @mbg.generated
     */
    int insert(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yj_product_category
     *
     * @mbg.generated
     */
    int insertSelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yj_product_category
     *
     * @mbg.generated
     */
    List<ProductCategory> selectByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yj_product_category
     *
     * @mbg.generated
     */
    ProductCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yj_product_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yj_product_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductCategory record);
}