package com.edityj.chapter2.pojo;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order.user_id
     *
     * @mbg.generated
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order.order_code
     *
     * @mbg.generated
     */
    private String order_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order.post
     *
     * @mbg.generated
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order.receiver
     *
     * @mbg.generated
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order.user_message
     *
     * @mbg.generated
     */
    private String user_message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order.create_date
     *
     * @mbg.generated
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order.pay_date
     *
     * @mbg.generated
     */
    private Date pay_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order.delivery_date
     *
     * @mbg.generated
     */
    private Date delivery_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order.confirm_date
     *
     * @mbg.generated
     */
    private Date confirm_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order.id
     *
     * @return the value of yj_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order.id
     *
     * @param id the value for yj_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order.user_id
     *
     * @return the value of yj_order.user_id
     *
     * @mbg.generated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order.user_id
     *
     * @param user_id the value for yj_order.user_id
     *
     * @mbg.generated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order.order_code
     *
     * @return the value of yj_order.order_code
     *
     * @mbg.generated
     */
    public String getOrder_code() {
        return order_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order.order_code
     *
     * @param order_code the value for yj_order.order_code
     *
     * @mbg.generated
     */
    public void setOrder_code(String order_code) {
        this.order_code = order_code == null ? null : order_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order.address
     *
     * @return the value of yj_order.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order.address
     *
     * @param address the value for yj_order.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order.post
     *
     * @return the value of yj_order.post
     *
     * @mbg.generated
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order.post
     *
     * @param post the value for yj_order.post
     *
     * @mbg.generated
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order.receiver
     *
     * @return the value of yj_order.receiver
     *
     * @mbg.generated
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order.receiver
     *
     * @param receiver the value for yj_order.receiver
     *
     * @mbg.generated
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order.mobile
     *
     * @return the value of yj_order.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order.mobile
     *
     * @param mobile the value for yj_order.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order.user_message
     *
     * @return the value of yj_order.user_message
     *
     * @mbg.generated
     */
    public String getUser_message() {
        return user_message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order.user_message
     *
     * @param user_message the value for yj_order.user_message
     *
     * @mbg.generated
     */
    public void setUser_message(String user_message) {
        this.user_message = user_message == null ? null : user_message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order.create_date
     *
     * @return the value of yj_order.create_date
     *
     * @mbg.generated
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order.create_date
     *
     * @param create_date the value for yj_order.create_date
     *
     * @mbg.generated
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order.pay_date
     *
     * @return the value of yj_order.pay_date
     *
     * @mbg.generated
     */
    public Date getPay_date() {
        return pay_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order.pay_date
     *
     * @param pay_date the value for yj_order.pay_date
     *
     * @mbg.generated
     */
    public void setPay_date(Date pay_date) {
        this.pay_date = pay_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order.delivery_date
     *
     * @return the value of yj_order.delivery_date
     *
     * @mbg.generated
     */
    public Date getDelivery_date() {
        return delivery_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order.delivery_date
     *
     * @param delivery_date the value for yj_order.delivery_date
     *
     * @mbg.generated
     */
    public void setDelivery_date(Date delivery_date) {
        this.delivery_date = delivery_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order.confirm_date
     *
     * @return the value of yj_order.confirm_date
     *
     * @mbg.generated
     */
    public Date getConfirm_date() {
        return confirm_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order.confirm_date
     *
     * @param confirm_date the value for yj_order.confirm_date
     *
     * @mbg.generated
     */
    public void setConfirm_date(Date confirm_date) {
        this.confirm_date = confirm_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order.status
     *
     * @return the value of yj_order.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order.status
     *
     * @param status the value for yj_order.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}