package com.edityj.chapter2.pojo;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order_item.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order_item.product_id
     *
     * @mbg.generated
     */
    private Integer product_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order_item.order_id
     *
     * @mbg.generated
     */
    private Integer order_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order_item.user_id
     *
     * @mbg.generated
     */
    private Integer user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_order_item.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order_item.id
     *
     * @return the value of yj_order_item.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order_item.id
     *
     * @param id the value for yj_order_item.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order_item.product_id
     *
     * @return the value of yj_order_item.product_id
     *
     * @mbg.generated
     */
    public Integer getProduct_id() {
        return product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order_item.product_id
     *
     * @param product_id the value for yj_order_item.product_id
     *
     * @mbg.generated
     */
    public void setProduct_id(Integer product_id) {
        this.product_id = product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order_item.order_id
     *
     * @return the value of yj_order_item.order_id
     *
     * @mbg.generated
     */
    public Integer getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order_item.order_id
     *
     * @param order_id the value for yj_order_item.order_id
     *
     * @mbg.generated
     */
    public void setOrder_id(Integer order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order_item.user_id
     *
     * @return the value of yj_order_item.user_id
     *
     * @mbg.generated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order_item.user_id
     *
     * @param user_id the value for yj_order_item.user_id
     *
     * @mbg.generated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_order_item.number
     *
     * @return the value of yj_order_item.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_order_item.number
     *
     * @param number the value for yj_order_item.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}