package com.edityj.chapter2.pojo;

public class ProductPropertyValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_product_property_value.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_product_property_value.product_id
     *
     * @mbg.generated
     */
    private Integer product_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_product_property_value.property_id
     *
     * @mbg.generated
     */
    private Integer property_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_product_property_value.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_product_property_value.id
     *
     * @return the value of yj_product_property_value.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_product_property_value.id
     *
     * @param id the value for yj_product_property_value.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_product_property_value.product_id
     *
     * @return the value of yj_product_property_value.product_id
     *
     * @mbg.generated
     */
    public Integer getProduct_id() {
        return product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_product_property_value.product_id
     *
     * @param product_id the value for yj_product_property_value.product_id
     *
     * @mbg.generated
     */
    public void setProduct_id(Integer product_id) {
        this.product_id = product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_product_property_value.property_id
     *
     * @return the value of yj_product_property_value.property_id
     *
     * @mbg.generated
     */
    public Integer getProperty_id() {
        return property_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_product_property_value.property_id
     *
     * @param property_id the value for yj_product_property_value.property_id
     *
     * @mbg.generated
     */
    public void setProperty_id(Integer property_id) {
        this.property_id = property_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_product_property_value.value
     *
     * @return the value of yj_product_property_value.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_product_property_value.value
     *
     * @param value the value for yj_product_property_value.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}