package com.edityj.chapter2.pojo;

public class ProductPropertyValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_product_property_value.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_product_property_value.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_product_property_value.property_id
     *
     * @mbg.generated
     */
    private Integer propertyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_product_property_value.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_product_property_value.id
     *
     * @return the value of yj_product_property_value.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_product_property_value.id
     *
     * @param id the value for yj_product_property_value.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_product_property_value.product_id
     *
     * @return the value of yj_product_property_value.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_product_property_value.product_id
     *
     * @param productId the value for yj_product_property_value.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_product_property_value.property_id
     *
     * @return the value of yj_product_property_value.property_id
     *
     * @mbg.generated
     */
    public Integer getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_product_property_value.property_id
     *
     * @param propertyId the value for yj_product_property_value.property_id
     *
     * @mbg.generated
     */
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_product_property_value.value
     *
     * @return the value of yj_product_property_value.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_product_property_value.value
     *
     * @param value the value for yj_product_property_value.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}