package com.edityj.chapter2.pojo;

public class ProductImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_product_image.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_product_image.product_id
     *
     * @mbg.generated
     */
    private Integer product_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yj_product_image.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_product_image.id
     *
     * @return the value of yj_product_image.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_product_image.id
     *
     * @param id the value for yj_product_image.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_product_image.product_id
     *
     * @return the value of yj_product_image.product_id
     *
     * @mbg.generated
     */
    public Integer getProduct_id() {
        return product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_product_image.product_id
     *
     * @param product_id the value for yj_product_image.product_id
     *
     * @mbg.generated
     */
    public void setProduct_id(Integer product_id) {
        this.product_id = product_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yj_product_image.type
     *
     * @return the value of yj_product_image.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yj_product_image.type
     *
     * @param type the value for yj_product_image.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}